[package]
name = "random-tag"
version = "0.1.10"
edition = "2021"
license = "MIT"
authors = ["Gleb Chipiga"]
keywords = ["cli", "random", "random-generation"]
categories = ["command-line-interface", "command-line-utilities"]
description = "Generate random tags"
repository = "https://github.com/gleb-chipiga/random-tag"

[dependencies]
anyhow = "1.0"
rand = "0.8"
clap = { version = "3.0", features = ["default", "derive", "cargo"] }
